config/routes.rb
VirtualLibrary::Application.routes.draw do


  resources :users, except: [:index, :destroy]
  resources :sessions
  
  resources :books do
    resources :reviews, except: [:edit, :update, :destroy]
    post 'borrow', on: :member
  end

  resources :book_histories

  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  get "users/edit"

  get "sesssions/create"
  get "sessions/destroy"


 
  root to:  'books#index'
  resources :pages, except: [:index, :destroy]
  resources "contacts", only: [:new, :create]

end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password

  has_many :books

  validates :name, presence: true, uniqueness: true
  validates :last_name, presence: true, uniqueness: true
  validates :email, presence: true, uniqueness: true
  validates :password, confirmation: true
  validates :password, :length => { :in => 6..20 }


  #
  # Instance methods
  #

  def first_name
    name.present? ? name.split(/\s+/).first : "Unknown"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :authorize
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @title = @user.name
    @books = @user.books
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json

  def create
  
  @user = User.new(user_params)
  if verify_recaptcha() && @user.save
    session[:user_id] = @user.id
    redirect_to root_url, notice: "Thank you for signing up!"
  else
    flash.delete(:recaptcha_error)
    redirect_to signup_path, alert: "Sorry, fill all fields."
  end
end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to root_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :last_name, :email, :password, :password_confirmation)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.haml
= form_for(@user) do |f|
  - if @user.errors.any?
    #error_explanation
      %h2
        = pluralize(@user.errors.count, "error")
        prohibited this book from being saved:
    %ul
      - @user.errors.full_messages.each do |msg|
        %li= msg
  .field
    = f.label :name
    %br
      = f.text_field :name, :required => true
  .field
    = f.label :last_name
    %br
      = f.text_field :last_name, :required => true
  .field
    = f.label :email
    %br
      = f.text_field :email, :required => true, :pattern => '[^@]+@[^@]+\.[a-zA-Z]{2,6}'
  .field
    = f.label :password
    %br
      = f.password_field :password
    %br
    = f.label :password_confirmation
    %br
      = f.password_field :password_confirmation
  .actions
    = f.submit "Edit Profile"

app/views/users/edit.html.haml
.container
  .row
  .col-md-3
  .col-md-6
    %p
    #loginform/
    = render 'form'
    %br
    = link_to 'My Library', @user
  

app/views/users/index.html.haml
%h1 Listing users
%table
  %thead
    %tr
      %th Name
      %th
      %th
      %th
  %tbody
    - @users.each do |user|
      %tr
        %td= user.name
        %td= link_to 'Show', user
        %td= link_to 'Edit', edit_user_path(user)
        %td= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' }
%br
  = link_to 'New User', new_user_path

app/views/users/new.html.haml
.container-fluid
  .row
    .col-md-2.col-md-offset-4
      #joinform/
      %h3 New Member
      %p
      You must be a member of the
      %a{:href => "sanjoseatheists.com"} Atheist Community of San Jose
      to join. Please use your <b>FULL NAME</b>.
      = form_for(@user) do |f|
        - f.error_messages
        .field
          = f.label :name
          %br
            = f.text_field :name, :required => true
        .field
          = f.label :last_name
          %br
          = f.text_field :last_name, :required => true
        .field
          = f.label :email
          %br
            = f.text_field :email, :required => true, :pattern => '[^@]+@[^@]+\.[a-zA-Z]{2,6}'
        .field
          = f.label :password
          %br
            = f.password_field :password
        %div
          = f.label :password_confirmation
          %br
            = f.password_field :password_confirmation

            = recaptcha_tags
        .actions
          = f.submit
    .col.md-6

app/views/users/show.html.haml
.container-fluid
  .row
  .col-md-12
    #bookstitle You have #{@user.books.count} books in your library
    - if @books.empty?
      %span.text-warning You haven't added books yet!
    - else
    %table#mylibrary.display
      %thead
        %tr
          %th Cover
          %th Title
          %th Description
          %th Author
          %th Change
          %th Status
          %th
      %tbody
        - @books.each do |book|
          %tr
            %td
              %img{:align => "center", :src => book.image_url, :vspace => "8", :width => 60, :height => 80}/
            %td= link_to book.title, book
            %td= truncate book.description, :length=>200
            %td= book.author
            %td= link_to 'Edit', edit_book_path(book), class: 'btn btn-default'
            %td
              - borrowed = book.get_borrowed
              - if book.is_borrowed?
                = button_to "Return book", borrowed, method: :patch, class: "btn", class: 'btn btn-success'
              - else
                %p Available
            %td= link_to "Delete", book, :method => :delete, :confirm => "Are you sure?", class: 'btn btn-danger'