config/routes.rb
VirtualLibrary::Application.routes.draw do


  resources :users, except: [:index, :destroy]
  resources :sessions
  
  resources :books do
    resources :reviews, except: [:edit, :update, :destroy]
    post 'borrow', on: :member
  end

  resources :book_histories

  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  get "users/edit"

  get "sesssions/create"
  get "sessions/destroy"


 
  root to:  'books#index'
  resources :pages, except: [:index, :destroy]
  resources "contacts", only: [:new, :create]

end

app/views/pages/_form.html.haml
= form_for(@page) do |f|
  - if @page.errors.any?
    #error_explanation
      %h2
        = pluralize(@page.errors.count, "error")
        prohibited this page from being saved:
      %ul
        - @page.errors.full_messages.each do |msg|
          %li= msg
  .field
    = f.text_field :title
  .field
    = f.text_area :content, cols: 75, rows:20
  .actions
    = f.submit

app/views/pages/edit.html.erb
<h1>Editing page</h1>

<%= render 'form' %>

<%= link_to 'Show', @page %> |
<%= link_to 'Back', pages_path %>

app/views/pages/edit.html.haml
%h3 Editing page
= render 'form'
= link_to 'Show', @page
|
\#{link_to 'Back', pages_path}

app/views/pages/index.html.erb
<h1>Listing pages</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Content</th>
      <th>Sort order</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @pages.each do |page| %>
      <tr>
        <td><%= page.title %></td>
        <td><%= page.content %></td>
        <td><%= page.sort_order %></td>
        <td><%= link_to 'Show', page %></td>
        <td><%= link_to 'Edit', edit_page_path(page) %></td>
        <td><%= link_to 'Destroy', page, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Page', new_page_path %>

app/views/pages/index.html.haml
%h1 Listing pages
%table
  %thead
    %tr
      %th Title
      %th Content
      %th Sort order
      %th
      %th
      %th
  %tbody
    - @pages.each do |page|
      %tr
        %td= page.title
        %td= page.content
        %td= page.sort_order
        %td= link_to 'Show', page
        %td= link_to 'Edit', edit_page_path(page)
        %td= link_to 'Destroy', page, method: :delete, data: { confirm: 'Are you sure?' }
%br
  = link_to 'New Page', new_page_path

app/views/pages/new.html.erb
<h1>New page</h1>

<%= render 'form' %>

<%= link_to 'Back', pages_path %>

app/views/pages/new.html.haml
%h1 New page
= render 'form'
= link_to 'Back', pages_path

app/views/pages/show.html.haml
.container-fluid
	.row
		.col-med-8-col-push
		.well
			%h3
				= @page.title
				%p{:style => "text-align: left"}
				= (@page.content).html_safe
				%p
				= link_to 'Back', books_path
				.col-med-4-col.pull
				.well