config/routes.rb
VirtualLibrary::Application.routes.draw do


  resources :users, except: [:index, :destroy]
  resources :sessions
  
  resources :books do
    resources :reviews, except: [:edit, :update, :destroy]
    post 'borrow', on: :member
  end

  resources :book_histories

  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  get "users/edit"

  get "sesssions/create"
  get "sessions/destroy"


 
  root to:  'books#index'
  resources :pages, except: [:index, :destroy]
  resources "contacts", only: [:new, :create]

end

app/models/book.rb
require 'model_helper'
class Book < ActiveRecord::Base
  include ModelHelper

  belongs_to :user
  has_many :reviews, dependent: :destroy
  has_many :book_histories, dependent: :destroy
  has_many :book_categories, dependent: :destroy
  has_many :categories, through: :book_categories

  validates :title, presence: true

  # Instance methods
  def get_borrowed
  book_histories.where(is_returned: false).last
  end

  def is_borrowed?
  get_borrowed.present?
  end


  def borrower_id
    book_histories.last.user_id
  end


  def get_latest_book_history(user_id) 
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: [:show, :edit, :update, :destroy]

  # GET /books
  # GET /books.json
  def index
    @books = Book.all
  end

  # GET /books/1
  # GET /books/1.json
  def show
    @book = Book.find(params[:id])
    @review = Review.new(book_id: @book.id)
    @book_history = BookHistory.new(book_id: @book.id, user_id: current_user.id)
  end

  # GET /books/new
  def new
    @book = Book.new
  end

  # GET /books/1/edit
  def edit
  end

  # POST /books
  # POST /books.json
  def create
    @book = Book.new(book_params.merge(user_id: current_user.id))
    @book.user = current_user
    respond_to do |format|
      if @book.save
        format.html { redirect_to @book, notice: 'Your book was successfully added!' }
        format.json { render action: 'show', status: :created, location: @book }
      else
        format.html { render action: 'new' }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /books/1
  # PATCH/PUT /books/1.json
  def update
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to @book, notice: 'Your book was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1
  # DELETE /books/1.json
  def destroy
    @book.destroy
    respond_to do |format|
      format.html { redirect_to books_url }
      format.json { head :no_content }
    end
  end

  def get_categories
    get_categories
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def book_params
      params.require(:book).permit(:title, :description, :image_url, :isbn, :author,
                                   { category_ids: [] })
    end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_form.html.haml
= form_for @book do |f|
  - if @book.errors.any?
    #error_explanation
      %h2
        = pluralize(@book.errors.count, "error")
        prohibited this book from being saved:
      %ul
        - @book.errors.full_messages.each do |msg|
          %li= msg
  .field
    = f.label :title
    %br
      = f.text_field :title,:size => "40"
  .field
    = f.label :description
    %br
      = f.text_area :description,:cols => "40", :rows => "6"
  .field
    = f.label :image_url
    %br
      = f.text_field :image_url,:size => "40"
  .field
    = f.label :isbn
    %br
    = f.text_field :isbn
  .field
    = f.label :author
    %br
      = f.text_field :author,:size => "40"
  .field
    = f.label :category
    .field
    = f.collection_select :category_ids, @book.get_all_categories, :id, :name, {}, multiple: true
  .actions
    = f.submit "Add/Update Book"

app/views/books/edit.html.haml
.container
  .row
    .col-md-3
    .col-md-6
      %p
        #bookshow/
      = render 'form'
      = link_to 'Show', @book |
      = link_to 'Back', books_path

app/views/books/index.html.haml
.container-fluid
  .row
  .col-md-12
    #bookstitle Books in the Library
    - if @books.empty?
      %span.text-warning There are no books!
    - else
    %table#books.display
      %thead
        %tr
          %th Cover
          %th Title
          %th Author
          %th Categories
          %th Description
          %th Status
          %th Owner
      %tbody
        -@books.each do |book| 
          %tr
            %td
              %img{:align => "left", :src => book.image_url, :vspace => "8", :width => 60, :height => 80}/
            %td= link_to book.title, {:action => 'show', :id => book.id}
            %td= book.author
            %td= book.category_names
            %td= truncate book.description, :length=>200
            %td
              - borrowed = book.get_borrowed
              - if book.is_borrowed?
                %br Unavailable
              -else
                %br Available
            %td= book.user_name + ' ' + book.user.last_name

app/views/books/new.html.haml
.container
  .row
    .col-md-3
    .col-md-6
      %p
        #bookshow/
      %p
      = render 'form'
      = link_to 'Back', books_path
    .col-md-3

app/views/books/show.html.haml
.container
  .row
    .col-md-5
      #bookshow
        %h4
          = @book.title
        %p
          = truncate @book.description, :length=>720
        %p
          %img{:align => "left", :height => "130", :hspace => "8", :src => @book.image_url, :width => "110"}/
        %p
          %strong Isbn:
          = @book.isbn
        %p
          %strong Author:
          = @book.author
        %p
          %strong Owner:
          = @book.user_name + ' ' + @book.user.last_name
        %p
          %strong Rate this book:
          .rw-ui-container
        %p
          = link_to "Write Review", new_book_review_path(@book)
        %p
          = link_to pluralize(@book.reviews.size, "Review"), book_reviews_path(@book)
        = link_to 'Back', books_path
    .col-md-7
      %table{:align => "right"}
        %tr
          %td{:align => "center"}
            - if true && @book.is_borrowed?
              %p This book is not available.
            - else
              = form_for @book_history do |f|
                = f.hidden_field :book_id
                = f.hidden_field :user_id
                = f.submit "Borrow", class: 'btn btn-success'
        %tr
          %td{:align => "center"}
            = image_tag 'openbook.jpeg'
        %tr
          %td{:align => "center"}
            %p= @book.title
    :javascript
      (function(d, t, e, m){
        // Async Rating-Widget initialization.
          window.RW_Async_Init = function(){
              RW.init({
                  huid: "149932",
                  uid: "397dfec8b894b41fcf866e91b8cb0a04",
                  source: "website",
                  options: {
                      "size": "medium",
                      "style": "ratingwidget"
                  }
              });
              RW.render();
          };
      
          // Append Rating-Widget JavaScript library.
          var rw, s = d.getElementsByTagName(e)[0], id = "rw-js",
              p = d.location.protocol, a = ("https:" == p ? "secure." +
              m + "js/" : "js." + m), ck = "Y" + t.getFullYear() + "M" +
              t.getMonth() + "D" + t.getDate();
          if (d.getElementById(id)) return;
          rw = d.createElement(e);
          rw.id = id; rw.async = true; rw.type = "text/javascript";
          rw.src = p + "//" + a + "external.min.js?ck=" + ck;
          s.parentNode.insertBefore(rw, s);
          }(document, new Date(), "script", "rating-widget.com/"));