config/routes.rb
VirtualLibrary::Application.routes.draw do


  resources :users, except: [:index, :destroy]
  resources :sessions
  
  resources :books do
    resources :reviews, except: [:edit, :update, :destroy]
    post 'borrow', on: :member
  end

  resources :book_histories

  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  get "users/edit"

  get "sesssions/create"
  get "sessions/destroy"


 
  root to:  'books#index'
  resources :pages, except: [:index, :destroy]
  resources "contacts", only: [:new, :create]

end

app/views/layouts/_flash.html.haml
- flash.each do |name, msg|
  - if msg.is_a?(String)
    = content_tag :div, msg, :class => "flash_#{name}"

app/views/layouts/_footer.html.haml
.container-fluid
  .row
    .col-med-12 
      #footer &copy;Atheists Community of San Jose Virtual Library

app/views/layouts/_header.html.haml
.container-fluid
  .row
    .col-md-7
      #header
      = link_to(image_tag("virtuallibrarylogo.jpg", class: 'img-responsive', :alt=> "logo",:title=> "Home", :float => "left"),"/")
    .col-md-2
      #bookicon
      %div{:style => "text-align: center"}
        = image_tag 'bookicon.jpeg' 
        %br/
        = link_to "Add a Book", new_book_path, class: 'btn btn-default btn-lg' 
    .col-md-3
      - if current_user
        %h5{:align => "right"}/ 
        Welcome, #{current_user.name}!
      - else
        %span.fa-stack.fa-lg
          %i.fa.fa-square-o.fa-stack-2x
          %i.fa.fa-spinner.fa-stack-1x
        = link_to "Log In", login_path
      %p{:style => "text-align: right"}/
      = link_to "Home", books_path 
      %span.fa-stack.fa-lg
        %i.fa.fa-square-o.fa-stack-2x
        %i.fa.fa-home.fa-stack-1x
      %br
      =link_to "About", '/pages/1' 
      %span.fa-stack.fa-lg
        %i.fa.fa-square-o.fa-stack-2x
        %i.fa.fa-user.fa-stack-1x
      %br
      = link_to "My Library", current_user 
      %span.fa-stack.fa-lg
        %i.fa.fa-square-o.fa-stack-2x
        %i.fa.fa-coffee.fa-stack-1x
      %br
      = link_to "Edit Profile", edit_user_path(current_user)
      %span.fa-stack.fa-lg
        %i.fa.fa-square-o.fa-stack-2x
        %i.fa.fa-laptop.fa-stack-1x
      %br
      = link_to "Contact", new_contact_path
      %span.fa-stack.fa-lg
        %i.fa.fa-square-o.fa-stack-2x
        %i.fa.fa-pencil.fa-stack-1x
      %br
      = link_to "Log Out", logout_path 
      %span.fa-stack.fa-lg
        %i.fa.fa-square-o.fa-stack-2x
        %i.fa.fa-power-off.fa-stack-1x
                
            
    
          
       

      
  

app/views/layouts/application.html.haml
!!!
%html
  %head>
    %title VirtualLibrary
    = csrf_meta_tags
    = stylesheet_link_tag  "application", media: "all"
    = javascript_include_tag "application"	
    %link{:href => "//netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css", :rel => "stylesheet"}
    %link{:href => "//cdn.datatables.net/1.10.0-beta.1/css/jquery.dataTables.css", :rel => "stylesheet"}
    %link{:href => "//code.jquery.com/ui/1.10.4/themes/smoothness/jquery-ui.css", :rel => "stylesheet"}
  %body
    = render 'layouts/header'
    = render 'layouts/flash'
    = yield
    = render 'layouts/footer'